// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import type { BaseHttpRequest } from './core/BaseHttpRequest';
import type { HelloControllerHelloResponse } from './types.gen';

export class HelloService {
    constructor(public readonly httpRequest: BaseHttpRequest) { }
    
    /**
     * Say hello
     * @returns string
     * @throws ApiError
     */
    public hello(): CancelablePromise<HelloControllerHelloResponse> {
        return this.httpRequest.request({
            method: 'GET',
            url: '/api/hello'
        });
    }
    
}